require('dotenv').config();
const pool=require('../src/config/db');
const DEPARTMENTS=[
['AE','Aeronautical Engineering'],['AIML','Artificial Intelligence & Machine Learning'],['AERO','Aerospace Engineering'],['CHE','Chemical Engineering'],['CSE','Computer Science & Engineering'],['CSD','Computer Science & Design'],['CSDDS','Computer Science & Engineering (Data Science)'],['CIVIL','Civil Engineering'],['ECE','Electronics & Communication Engineering'],['EEE','Electrical & Electronics Engineering'],['IIOT','Industrial IoT'],['ISE','Information Science & Engineering'],['ME','Mechanical Engineering'],['VLSI','Electronics Engineering (VLSI Design & Technology)'],['ECA','Electronics & Communication (Advanced Communication Technology)']
];
const LOCATIONS=[
['Main Gate','entrance',12.98360,77.76170,'Primary campus entrance'],['Block A','academic',12.98388,77.76190,'Academic block'],['Block B','academic',12.98415,77.76215,'Engineering block'],['Auditorium 1','academic',12.98430,77.76180,'Main auditorium'],['Auditorium 2','academic',12.98445,77.76245,'Secondary auditorium'],['Seminar Hall','academic',12.98405,77.76145,'Seminars and workshops'],['Library','academic',12.98375,77.76255,'Central library'],['Canteen','food',12.98320,77.76225,'Main canteen'],['Admin Office','admin',12.98378,77.76130,'Administration'],['Examination Cell','admin',12.98392,77.76115,'Examination Cell'],['Placement Cell','admin',12.98465,77.76205,'Placement Cell'],['Medical Room','medical',12.98325,77.76170,'First aid and medical support'],['Labs Complex','academic',12.98435,77.76275,'Engineering laboratories'],['Parking','parking',12.98310,77.76140,'Campus parking']
];
const EDGES=[['Main Gate','Block A',90],['Main Gate','Admin Office',130],['Main Gate','Parking',60],['Block A','Block B',100],['Block A','Seminar Hall',80],['Block B','Auditorium 2',140],['Block B','Labs Complex',110],['Block B','Library',90],['Seminar Hall','Auditorium 1',60],['Seminar Hall','Examination Cell',50],['Admin Office','Examination Cell',40],['Admin Office','Medical Room',70],['Library','Canteen',120],['Library','Placement Cell',160],['Auditorium 1','Library',130],['Auditorium 2','Labs Complex',90],['Auditorium 2','Placement Cell',100],['Canteen','Parking',100],['Medical Room','Canteen',90]];
(async()=>{try{
 await pool.query("INSERT IGNORE INTO departments (code,name) VALUES ?",[DEPARTMENTS]);
 for(const [code] of DEPARTMENTS){for(const [yr,sec] of [[1,'A'],[1,'B'],[2,'A'],[3,'A'],[4,'A']]){const [[d]]=await pool.query('SELECT id FROM departments WHERE code=?',[code]);await pool.query('INSERT IGNORE INTO classes (department_id,year_of_study,section,name) VALUES (?,?,?,?)',[d.id,yr,sec,`${code} ${yr}${yr===1?'st':yr===2?'nd':yr===3?'rd':'th'} Year — Section ${sec}`]);}}
 await pool.query("INSERT IGNORE INTO locations (name,category,lat,lng,description) VALUES ?",[LOCATIONS]);
 for(const [a,b,d] of EDGES){const [[x]]=await pool.query('SELECT id FROM locations WHERE name=?',[a]);const [[y]]=await pool.query('SELECT id FROM locations WHERE name=?',[b]);if(!x||!y)continue;const w=Math.round(d/1.2);await pool.query('INSERT IGNORE INTO location_edges (from_location_id,to_location_id,distance_meters,walk_seconds) VALUES (?,?,?,?)',[x.id,y.id,d,w]);await pool.query('INSERT IGNORE INTO location_edges (from_location_id,to_location_id,distance_meters,walk_seconds) VALUES (?,?,?,?)',[y.id,x.id,d,w]);}
 console.log('CampusPulse+ campus data ready.');
}catch(e){console.error('Campus bootstrap failed:',e.message);process.exitCode=1;}finally{await pool.end();}})();
