import React,{useEffect,useMemo,useState} from 'react';import {useSearchParams,Link} from 'react-router-dom';import {MapContainer,TileLayer,Marker,Polyline,Popup,useMap} from 'react-leaflet';import L from 'leaflet';import {api} from '../api/client';import {useAuth} from '../context/AuthContext';import {useSocket} from '../context/SocketContext';import {Loading} from '../components/States';
const icon=new L.Icon({iconUrl:'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png',shadowUrl:'https://unpkg.com/leaflet@1.9.4/dist/images/marker-shadow.png',iconSize:[25,41],iconAnchor:[12,41]});
const QUICK=['Auditorium 1','Auditorium 2','Seminar Hall','Library','Admin Office','Placement Cell','Medical Room','Canteen'];
const MAP_FALLBACK=[
 ['Main Gate','entrance',12.98360,77.76170],['Block A','academic',12.98388,77.76190],['Block B','academic',12.98415,77.76215],['Auditorium 1','academic',12.98430,77.76180],['Auditorium 2','academic',12.98445,77.76245],['Seminar Hall','academic',12.98405,77.76145],['Library','academic',12.98375,77.76255],['Canteen','food',12.98320,77.76225],['Admin Office','admin',12.98378,77.76130],['Examination Cell','admin',12.98392,77.76115],['Placement Cell','admin',12.98465,77.76205],['Medical Room','medical',12.98325,77.76170],['Labs Complex','academic',12.98435,77.76275],['Parking','parking',12.98310,77.76140]
].map(([name,category,lat,lng],i)=>({id:`fallback-${i}`,name,category,lat,lng}));
function Recenter({center}){const map=useMap();useEffect(()=>{if(center)map.flyTo(center,17,{duration:.5});},[center,map]);return null;}
function walk(s){const m=Math.max(1,Math.round((s||0)/60));return `${m} min walk`;}
export default function CampusMap(){
 const {isAuthenticated}=useAuth();const {routeUpdate,clearRouteUpdate}=useSocket();const [params]=useSearchParams();const [locations,setLocations]=useState([]);const [fromId,setFromId]=useState('');const [toId,setToId]=useState(params.get('to')||'');const [route,setRoute]=useState(null);const [sessionId,setSessionId]=useState(null);const [loading,setLoading]=useState(true);const [calculating,setCalculating]=useState(false);const [error,setError]=useState('');const [query,setQuery]=useState('');const [notice,setNotice]=useState(null);
 useEffect(()=>{api.get('/navigation/locations').then(d=>{const rows=d.locations||[];setLocations(rows.length?rows:MAP_FALLBACK);const gate=(rows.length?rows:MAP_FALLBACK).find(x=>x.name==='Main Gate');if(gate&&!fromId)setFromId(String(gate.id));if(!rows.length)setError('Campus locations are not loaded yet. The page is showing the campus directory preview; run the database setup before calculating routes.');}).catch(e=>{setLocations(MAP_FALLBACK);setError(`Campus data could not be loaded. ${e.message}`)}).finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(!routeUpdate||!sessionId||routeUpdate.sessionId!==sessionId)return;setRoute(routeUpdate.route);setNotice(routeUpdate);clearRouteUpdate();},[routeUpdate,sessionId,clearRouteUpdate]);
 async function calc(){if(String(fromId).startsWith('fallback-')||String(toId).startsWith('fallback-')){setError('The campus preview is available, but live routing needs the database seed. Run the backend database setup, then refresh this page.');return;}if(!fromId||!toId||fromId===toId){setError('Choose two different locations.');return;}setCalculating(true);setError('');setNotice(null);try{const d=isAuthenticated?await api.post('/navigation/sessions',{from_location_id:Number(fromId),to_location_id:Number(toId)}):await api.get(`/navigation/route?from=${fromId}&to=${toId}`);setRoute(d.route);if(d.sessionId)setSessionId(d.sessionId);}catch(e){setRoute(null);setError(e.message);}finally{setCalculating(false);}}
 const filtered=locations.filter(l=>l.name.toLowerCase().includes(query.toLowerCase())).slice(0,8);const center=route?.path?.[0]?[Number(route.path[0].lat),Number(route.path[0].lng)]:[12.98394,77.76205];const line=route?.path?.map(p=>[Number(p.lat),Number(p.lng)])||[];
 if(loading)return <div className="container page"><Loading/></div>;
 return <div className="container page"><div className="row" style={{justifyContent:'space-between',gap:16,flexWrap:'wrap',marginBottom:18}}><div><div className="eyebrow">Navigate campus</div><h1 style={{fontSize:'clamp(34px,5vw,50px)',marginTop:6}}>Get there without guessing.</h1><p className="muted" style={{maxWidth:650}}>Use official campus locations and walking paths. When a verified venue changes during your journey, your active route can update automatically.</p></div><Link className="btn btn-secondary" to="/directory">Browse locations →</Link></div>
 <div className="map-layout"><aside className="detail-panel map-controls"><div className="field"><label htmlFor="map-search">Search a destination</label><input id="map-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try Auditorium, Library…" autoComplete="off"/></div>{query&&<div className="search-popover">{filtered.map(l=><button type="button" key={l.id} onClick={()=>{setToId(String(l.id));setQuery('')}}>{l.name}<span>{l.category}</span></button>)}{!filtered.length&&<p className="small muted" style={{padding:10}}>No matching campus location.</p>}</div>}
   <div className="row gap-3"><div className="field grow"><label htmlFor="map-from">From</label><select id="map-from" value={fromId} onChange={e=>setFromId(e.target.value)}><option value="">Select start</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div><button type="button" className="btn btn-ghost swap" onClick={()=>{const x=fromId;setFromId(toId);setToId(x)}} aria-label="Swap start and destination">↕</button></div>
   <div className="field"><label htmlFor="map-to">Destination</label><select id="map-to" value={toId} onChange={e=>setToId(e.target.value)}><option value="">Select destination</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div>
   <button type="button" className="btn btn-primary btn-block btn-lg" onClick={calc} disabled={calculating||!fromId||!toId}>{calculating?'Calculating…':'Show walking route'}</button>
   <div className="quick-dest" style={{marginTop:14}}>{QUICK.map(name=>{const loc=locations.find(l=>l.name===name);return loc?<button type="button" className="pill-tab" key={name} onClick={()=>setToId(String(loc.id))}>{name}</button>:null})}</div>
   {notice&&<div className="alert alert-important" style={{marginTop:14}}><div><strong>Route updated</strong><div className="small">{notice.reason||'Verified campus change'} — your destination moved from {notice.from||'the previous venue'} to {notice.to||'the new venue'}.</div></div></div>}
   {error&&<div className="form-error" style={{marginTop:14}}>{error}</div>}
   {route&&!calculating&&<div className="route-summary" style={{marginTop:14}}><p className="small faint">YOUR ROUTE</p><p className="small" style={{fontWeight:700,margin:'4px 0 10px'}}>{route.path.map(p=>p.name).join(' → ')}</p><div className="row gap-5"><span className="small"><strong>{route.distanceMeters} m</strong> distance</span><span className="small"><strong>{walk(route.walkSeconds)}</strong></span></div></div>}
   </aside><section className="map-visual"><MapContainer center={center} zoom={17} style={{height:'100%',minHeight:570,width:'100%'}} scrollWheelZoom><Recenter center={center}/><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{locations.map(l=><Marker key={l.id} position={[Number(l.lat),Number(l.lng)]} icon={icon}><Popup><strong>{l.name}</strong><br/><span className="small muted">{l.category}</span><br/><button className="btn btn-secondary btn-sm" style={{marginTop:8}} onClick={()=>setToId(String(l.id))}>Set as destination</button></Popup></Marker>)}{line.length>1&&<Polyline positions={line} pathOptions={{color:'#2D67D5',weight:6,opacity:.82}}/>}</MapContainer></section></div>
 {!isAuthenticated&&<div className="card-flat small muted" style={{marginTop:14}}>Live automatic rerouting is available after you sign in, because the platform needs an active navigation session tied to your account.</div>}
 </div>
}
