import React,{useEffect,useState} from 'react';import {useParams,Link} from 'react-router-dom';import {api} from '../api/client';import {Loading,ErrorState,EmptyState} from '../components/States';import {useAuth} from '../context/AuthContext';
export default function ClubDetail(){
 const {id}=useParams();const {isAuthenticated,clubLeadership}=useAuth();const [club,setClub]=useState(null);const [events,setEvents]=useState([]);const [media,setMedia]=useState([]);const [links,setLinks]=useState([]);const [joined,setJoined]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);
 function load(){setLoading(true);Promise.all([api.get(`/clubs/${id}`),api.get(`/media/club/${id}`).catch(()=>({media:[]})),api.get(`/links/club/${id}`).catch(()=>({links:[]}))]).then(([c,m,l])=>{setClub(c.club);setEvents(c.upcomingEvents);setMedia(m.media);setLinks(l.links||c.club?.links||[]);}).catch(()=>setError(true)).finally(()=>setLoading(false));}useEffect(load,[id]);
 async function join(){try{await api.post(`/clubs/${id}/join`,{});setJoined(true);}catch{}}
 const canManage=clubLeadership.some(c=>Number(c.club_id)===Number(id));
 if(loading)return <div className="container page"><Loading/></div>;if(error||!club)return <div className="container page"><ErrorState onRetry={load}/></div>;
 return <div className="container page">
   <Link to="/clubs" className="small muted">← All clubs</Link>
   <section className="detail-hero"><div className="eyebrow" style={{color:'#bcd0ff'}}>OFFICIAL CLUB</div><div className="row" style={{justifyContent:'space-between',gap:20,flexWrap:'wrap',marginTop:8}}><div><span className="badge" style={{background:'rgba(255,255,255,.15)',color:'#fff'}}>{club.category}</span><h1 style={{fontSize:'clamp(34px,5vw,54px)',marginTop:10}}>{club.name}</h1><p style={{maxWidth:720,marginTop:10,color:'#dce7fb',fontSize:16}}>{club.description}</p></div>{isAuthenticated&&<button className="btn" style={{background:'#fff',color:'var(--cp-dark)'}} disabled={joined} onClick={join}>{joined?'Joined ✓':'Join club'}</button>}</div></section>
   <div className="detail-grid"><div className="stack gap-4">
     <section className="detail-panel"><h3>Club team</h3><div className="row gap-5" style={{flexWrap:'wrap',marginTop:16}}><div><span className="small faint">Faculty Coordinator</span><strong>{club.coordinator_name||'Not assigned'}</strong></div><div><span className="small faint">President</span><strong>{club.president_name}</strong></div><div><span className="small faint">Vice President</span><strong>{club.vp_name||'Not assigned'}</strong></div></div></section>
     <section className="detail-panel"><div className="row" style={{justifyContent:'space-between',marginBottom:14}}><div><h3>Upcoming events</h3><p className="small muted">Workshops, activities and drives from this club.</p></div>{canManage&&<Link className="btn btn-secondary btn-sm" to="/club-dashboard">Manage club</Link>}</div>{!events.length?<EmptyState title="No upcoming events" body="Check back soon."/>:<div className="stack gap-2">{events.map(e=><Link key={e.id} to={`/events/${e.id}`} className="card card-interactive row" style={{justifyContent:'space-between'}}><div><strong>{e.title}</strong><div className="small muted">{new Date(e.starts_at).toLocaleString(undefined,{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</div></div><span className="text-link">Open →</span></Link>)}</div>}</section>
   </div><aside className="stack gap-4">
     <section className="detail-panel"><h3>Club links</h3>{links.length?<div className="stack gap-2" style={{marginTop:12}}>{links.map(l=><a className="btn btn-secondary" key={l.id} href={l.url} target="_blank" rel="noreferrer">{l.label} ↗</a>)}</div>:<p className="small muted" style={{marginTop:10}}>Club links will appear here.</p>}</section>
     <section className="detail-panel"><h3>Photos & posters</h3>{media.length?<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,marginTop:12}}>{media.map(m=><img key={m.id} src={m.url} alt={m.caption||club.name} style={{width:'100%',height:120,objectFit:'cover',borderRadius:12}}/>)}</div>:<div className="club-card-image" style={{height:180,marginTop:12,borderRadius:14}}><img src="/assets/club-illustration.svg" alt="Club activity illustration"/></div>}</section>
   </aside></div>
 </div>
}
