import React,{useEffect,useState} from 'react';import {useNavigate} from 'react-router-dom';import {api} from '../api/client';import {useAuth} from '../context/AuthContext';
const CATEGORIES=[['exam','Exam'],['academic','Academic'],['emergency','Emergency'],['club','Club'],['workshop','Workshop'],['competition','Competition'],['transportation','Transport'],['facilities','Facilities'],['general','General']];
export default function ComposeAnnouncement(){
 const {user,clubLeadership}=useAuth();const navigate=useNavigate();const isAdmin=user?.role==='admin';const isTeacher=user?.role==='teacher';const leadershipClub=clubLeadership[0];const isClubLeader=!!leadershipClub;
 const [form,setForm]=useState({title:'',body:'',category:'general',urgency:'normal',target_scope:isAdmin?'campus':isTeacher?'department':'club',target_department:user?.department||'',target_year:'',target_class_id:'',target_club_id:leadershipClub?.club_id||'',target_topic_id:'',safe_location_id:'',instructions:''});
 const [departments,setDepartments]=useState([]),[classes,setClasses]=useState([]),[clubs,setClubs]=useState([]),[locations,setLocations]=useState([]),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{Promise.all([api.get('/auth/departments'),api.get('/auth/classes'),api.get('/clubs'),api.get('/navigation/locations')]).then(([d,c,cl,l])=>{setDepartments(d.departments);setClasses(c.classes);setClubs(cl.clubs);setLocations(l.locations);}).catch(e=>setError(e.message));},[]);
 const baseScopes=isAdmin?['campus','department','class','year','club','event']:isTeacher?['department','class']:[];
 const availableScopes=Array.from(new Set([...baseScopes,...(isClubLeader?['club','campus','event']:[])]));
 const scopedClasses=isTeacher?classes.filter(c=>c.department_name===user.department):classes;
 async function submit(e){e.preventDefault();setBusy(true);setError('');setSuccess('');try{const d=await api.post('/announcements',{...form,target_year:form.target_year?Number(form.target_year):null,target_class_id:form.target_class_id?Number(form.target_class_id):null,target_club_id:form.target_club_id?Number(form.target_club_id):null,target_event_id:null,target_topic_id:null,safe_location_id:form.safe_location_id?Number(form.safe_location_id):null});setSuccess(`Announcement sent to ${d.delivered} approved account${d.delivered===1?'':'s'}.`);setTimeout(()=>navigate('/announcements'),1300);}catch(err){setError(err.message);}finally{setBusy(false);}}
 return <div className="container page" style={{maxWidth:860}}><div className="eyebrow">Communication center</div><h1 style={{fontSize:'clamp(36px,5vw,52px)',marginTop:7}}>Send a clear campus message.</h1><p className="muted" style={{maxWidth:700,marginBottom:24}}>{isAdmin?'Use official campus-wide or targeted communication.':isClubLeader?`You have club responsibility for ${leadershipClub?.club_name||'your club'} and retain your normal ${isTeacher?'teacher':'student'} permissions.` : 'Teachers can message their own department or assigned class.'}</p>{error&&<div className="form-error">{error}</div>}{success&&<div className="form-success">{success}</div>}
 <form className="card" onSubmit={submit}><div className="field"><label htmlFor="ann-title">Headline</label><input id="ann-title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Auditorium 2 is now the exam venue" required/></div><div className="field"><label htmlFor="ann-body">Message</label><textarea id="ann-body" rows="6" value={form.body} onChange={e=>setForm({...form,body:e.target.value})} placeholder="Tell people what changed, when it applies, and what they should do next." required/></div>
 <div className="row gap-3" style={{flexWrap:'wrap'}}><div className="field grow"><label>Category</label><select value={form.category} onChange={e=>setForm({...form,category:e.target.value,urgency:e.target.value==='emergency'?'critical':form.urgency})}>{CATEGORIES.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></div><div className="field grow"><label>Urgency</label><select value={form.urgency} onChange={e=>setForm({...form,urgency:e.target.value})}><option>normal</option><option>important</option><option>critical</option></select></div></div>
 <div className="field"><label>Audience</label><select value={form.target_scope} onChange={e=>setForm({...form,target_scope:e.target.value,target_department:isTeacher?user.department:form.target_department,target_club_id:isClubLeader?(leadershipClub?.club_id||''):form.target_club_id})}>{availableScopes.map(s=><option key={s} value={s}>{s==='campus'?'Entire college':s==='department'?'My department':s==='class'?'Specific class / section':s==='year'?'Specific year':s==='club'?'Club members':'Event participants'}</option>)}</select></div>
 {form.target_scope==='department'&&<div className="field"><label>Department</label><select value={form.target_department} disabled={isTeacher} onChange={e=>setForm({...form,target_department:e.target.value})}>{departments.map(d=><option key={d.id} value={d.name}>{d.code} — {d.name}</option>)}</select></div>}
 {form.target_scope==='class'&&<div className="field"><label>Class / section</label><select required value={form.target_class_id} onChange={e=>setForm({...form,target_class_id:e.target.value})}><option value="">Select class</option>{scopedClasses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>}
 {form.target_scope==='year'&&<div className="field"><label>Year</label><select value={form.target_year} onChange={e=>setForm({...form,target_year:e.target.value})}><option value="">Select year</option>{[1,2,3,4].map(y=><option key={y} value={y}>{y}{y===1?'st':y===2?'nd':y===3?'rd':'th'} year</option>)}</select></div>}
 {form.target_scope==='club'&&<div className="field"><label>Club</label><select value={form.target_club_id} disabled={isClubLeader} onChange={e=>setForm({...form,target_club_id:e.target.value})}><option value="">Select club</option>{(isClubLeader?clubs.filter(c=>Number(c.id)===Number(leadershipClub.club_id)):clubs).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>}
 {form.category==='emergency'&&<div className="card-flat"><div className="field"><label>Direct recipients to</label><select value={form.safe_location_id} onChange={e=>setForm({...form,safe_location_id:e.target.value})}><option value="">No specific location</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></div><div className="field" style={{marginBottom:0}}><label>What should people do?</label><textarea value={form.instructions} onChange={e=>setForm({...form,instructions:e.target.value})} placeholder="Give simple, practical instructions."/></div></div>}
 <button className="btn btn-primary btn-block btn-lg" disabled={busy}>{busy?'Sending announcement…':'Send announcement'}</button></form></div>
}
