import React,{useEffect,useState} from 'react';import {Link} from 'react-router-dom';import {useAuth} from '../context/AuthContext';import {api} from '../api/client';import {Loading,EmptyState} from '../components/States';import {UrgencyBadge,CategoryBadge} from '../components/Badges';
function timeAgo(d){const x=(Date.now()-new Date(d))/1000;if(x<60)return'just now';if(x<3600)return`${Math.floor(x/60)}m ago`;if(x<86400)return`${Math.floor(x/3600)}h ago`;return`${Math.floor(x/86400)}d ago`;}
function formatEventTime(d){return new Date(d).toLocaleString(undefined,{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});}
export default function Dashboard(){const{user,clubLeadership}=useAuth();const[loading,setLoading]=useState(true);const[data,setData]=useState({a:[],e:[],n:[],c:[]});useEffect(()=>{Promise.all([api.get('/announcements'),api.get('/events?upcoming=true'),api.get('/notifications'),api.get('/clubs/joined')]).then(([a,e,n,c])=>setData({a:a.announcements||[],e:e.events||[],n:n.notifications||[],c:c.clubs||[]})).finally(()=>setLoading(false));},[]);if(loading)return <div className="container page"><Loading/></div>;const greeting=new Date().getHours()<12?'Good morning':new Date().getHours()<18?'Good afternoon':'Good evening';const top=data.a.slice(0,3);return <div className="container page">
<section className="dashboard-hero"><div><div className="eyebrow">Your campus, connected</div><h1>{greeting}, {user.full_name.split(' ')[0]}.</h1><p>Here is the information most relevant to your day — official alerts, upcoming events, clubs and directions.</p><div className="row gap-3" style={{marginTop:20,flexWrap:'wrap'}}><Link className="btn btn-primary" to="/announcements">View live alerts</Link><Link className="btn btn-secondary" to="/map">Navigate campus</Link></div></div><img src="/assets/campus-hero.svg" alt="CampusPulse+ live campus alert illustration"/></section>
{clubLeadership.length>0&&<div className="card-flat" style={{margin:'18px 0',display:'flex',gap:10,alignItems:'center',flexWrap:'wrap'}}><strong>Your club responsibility:</strong>{clubLeadership.map(c=><span className="badge badge-accent" key={`${c.club_id}-${c.role}`}>{c.role.replace('_',' ')} · {c.club_name}</span>)}<Link to="/club-dashboard" className="text-link" style={{marginLeft:'auto'}}>Open club tools →</Link></div>}
<div className="quick-grid"><Link to="/map" className="quick-tile quick-blue"><span>01</span><strong>Find a place</strong><p>Get a walking route to your next venue.</p></Link><Link to="/events" className="quick-tile quick-purple"><span>02</span><strong>See what’s happening</strong><p>Workshops, activities and campus events.</p></Link><Link to="/incidents/report" className="quick-tile quick-peach"><span>03</span><strong>Report a change</strong><p>Help verify a venue or campus incident.</p></Link></div>
<div className="dashboard-columns"><main><div className="section-heading"><div><h2>Important for you</h2><p>Newest official and relevant campus communication.</p></div><Link className="text-link" to="/announcements">See all</Link></div>{!top.length?<EmptyState title="You're all caught up" body="New campus alerts will appear here."/>:<div className="stack gap-3">{top.map(a=><article className={`alert-card ${a.urgency==='critical'?'critical':''}`} key={a.id}><div className="row" style={{justifyContent:'space-between',gap:10}}><div className="row gap-2"><UrgencyBadge urgency={a.urgency}/><CategoryBadge category={a.category}/></div><span className="small faint">{timeAgo(a.created_at)}</span></div><h3 style={{marginTop:10}}>{a.title}</h3><p className="small muted">{a.body}</p>{a.instructions&&<div className="action-strip"><strong>What to do:</strong> {a.instructions}</div>}{a.safe_location_id&&<Link className="btn btn-danger btn-sm" to={`/map?to=${a.safe_location_id}`} style={{marginTop:10}}>Get directions →</Link>}</article>)}</div>}
<div className="section-heading" style={{marginTop:34}}><div><h2>Coming up</h2><p>Make the most of campus this week.</p></div><Link className="text-link" to="/events">All events</Link></div>{!data.e.length?<EmptyState title="No upcoming events"/>:<div className="stack gap-2">{data.e.slice(0,4).map(e=><Link key={e.id} to={`/events/${e.id}`} className="event-row"><div><strong>{e.title}</strong><p>{e.club_name} · {formatEventTime(e.starts_at)}</p></div><span>→</span></Link>)}</div>}</main><aside><div className="section-heading"><div><h2>Your clubs</h2><p>Communities you have joined.</p></div><Link className="text-link" to="/clubs">Browse</Link></div>{!data.c.length?<EmptyState title="No clubs yet" body="Explore official clubs and join your community."/>:<div className="stack gap-2">{data.c.slice(0,5).map(c=><Link className="club-mini" key={c.id} to={`/clubs/${c.id}`}><span className="club-mini-icon">{c.name.slice(0,1)}</span><span><strong>{c.name}</strong><small>{c.upcoming_event_count||0} upcoming event{Number(c.upcoming_event_count)===1?'':'s'}</small></span><span>→</span></Link>)}</div>}
<div className="side-card" style={{marginTop:20}}><div className="eyebrow">New here?</div><h3>Learn the campus in minutes.</h3><p>Use New Student Mode for quick routes to the auditorium, seminar hall, exam cell and other essential places.</p><Link className="text-link" to="/welcome">Open campus guide →</Link></div></aside></div></div>}
